CLIENTE 

NOME = (30)
CPF = NUMERICO (11)
EMAIL = caracter (30)
TELEFONE = caracter (30)
ENDERECO = caracter (100)
SEXO = caracter (1)

/* PROCESSO DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS E MODELAGEM DE DADOS */
MODELAGEM CONCEITUAL = RASCUNHO
MODELAGEM LOGICA = QUALQUER PROGRAMA DE MODELAGEM

/* BRMW PRA FAZER O DESENHO DO BANCO DE DAODS */

/* FASE 03 - MODELAGEM FISICA */

/* CRIAÇÃO DO BANCO */
CREATE DATABASE PROJETO;

# USO DO BANCO DE DADOS
USE PROJETO;

# CRIANDO TABELA CLIENTE
CREATE TABLE CLIENTE ( /* SCRIPTS DE BANCO */
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    CPF NUMERIC(11) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    SEXO CHAR(1) NOT NULL
);

# VERIFICANDO TABELAS DO BANCO
SHOW TABLES

# VERIFICANDO ESTRUTURA DA TABELA
DESC CLIENTE

